2022-07-06 09:44:05,548 - count_word.py - [line:22] - ERROR - [日志信息]: asdfasdf
2022-07-06 09:48:52,742 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
2022-07-06 09:50:43,432 - Log.py - [line:183] - ERROR - [日志信息]: asdfasdf
2022-07-06 09:51:59,242 - Log.py - [line:183] - ERROR - [日志信息]: asdfasdf
2022-07-06 09:52:36,284 - Log.py - [line:183] - ERROR - [日志信息]: asdfasdf
2022-07-06 09:52:52,200 - Log.py - [line:183] - ERROR - [日志信息]: asdfasdf
2022-07-06 09:55:56,763 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
2022-07-06 09:56:15,091 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 09:59:41,523 - Log.py - [line:184] - ERROR - [日志信息]: asdfasdf
2022-07-06 10:00:30,229 - Log.py - [line:184] - ERROR - [日志信息]: asdfasdf
2022-07-06 10:02:32,978 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 10:14:44,741 - Log.py - [line:153] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 10:15:46,726 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:29:17,426 - Log.py - [line:183] - ERROR - [日志信息]: asdfasdf
2022-07-06 12:29:52,733 - Log.py - [line:155] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 12:30:46,036 - Log.py - [line:155] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:36:32,493 - Log.py - [line:155] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:42:50,891 - Log.py - [line:156] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 12:43:03,037 - Log.py - [line:156] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:47:13,538 - Log.py - [line:156] - ERROR - [日志信息]: asdfasdf
2022-07-06 12:50:23,366 - Log.py - [line:157] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 12:50:34,917 - Log.py - [line:157] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:51:54,125 - Log.py - [line:157] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:53:56,948 - Log.py - [line:157] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 12:54:04,052 - Log.py - [line:157] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:54:54,868 - Log.py - [line:157] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:55:32,972 - Log.py - [line:157] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 12:56:08,955 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
2022-07-06 12:59:24,548 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
2022-07-06 13:00:53,534 - Log.py - [line:199] - ERROR - [日志信息]: asdfasdf
2022-07-06 13:02:58,799 - Log.py - [line:199] - ERROR - [日志信息]: asdfasdf
2022-07-06 13:04:05,486 - Log.py - [line:171] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 13:04:33,803 - Log.py - [line:171] - ERROR - [日志信息]: name 'time' is not defined
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/Dataplat_API_auto_test/test_data/count_word.py", line 24, in <module>
    time.asdsd
NameError: name 'time' is not defined
2022-07-06 13:05:18,283 - Log.py - [line:160] - ERROR - [日志信息]: asdfasdf
NoneType: None
2022-07-06 13:06:18,227 - count_word.py - [line:26] - ERROR - [日志信息]: name 'time' is not defined
