[2023-02-13 14:30:16,189]-[readConfig.py]-[line:24]-ERROR: 配置文件读取失败！
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/API_auto_test/common/readConfig.py", line 18, in read_config
    f = open(file=file_path, mode='r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_robot_list'
[2023-02-13 18:22:09,545]-[readConfig.py]-[line:26]-ERROR: 配置文件读取失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\readConfig.py", line 20, in read_config
    f = open(file=file_path, mode='r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\PycharmProjects\\API_auto_test\\test_data\\test_data.yaml'
