[2023-02-13 14:30:16,189]-[readConfig.py]-[line:17]-INFO: 正在读取配置文件中...
[2023-02-13 14:30:16,189]-[readConfig.py]-[line:24]-ERROR: 配置文件读取失败！
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/API_auto_test/common/readConfig.py", line 18, in read_config
    f = open(file=file_path, mode='r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_robot_list'
[2023-02-13 14:31:07,688]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:31:07,690]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:31:30,874]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:31:30,876]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:31:54,602]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:31:54,603]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:32:59,646]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:32:59,669]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:33:54,936]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:33:54,938]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:34:25,252]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:34:25,254]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:34:55,434]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:34:55,437]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:35:19,213]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:35:19,215]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:35:42,371]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:35:42,373]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:36:12,072]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:36:12,074]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:37:25,006]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:37:25,008]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:37:56,795]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:37:56,797]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:38:46,740]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:38:46,743]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 14:39:50,149]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 14:39:50,151]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:47:03,497]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:47:03,499]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:47:31,567]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:47:31,569]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:48:15,228]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:48:15,230]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:49:09,686]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:49:09,687]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:49:22,187]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:49:22,189]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:50:49,923]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:50:49,925]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 16:59:27,340]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 16:59:27,343]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 18:21:23,489]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 18:21:23,491]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 18:21:23,491]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 18:21:23,493]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 18:22:09,543]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 18:22:09,545]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 18:22:09,545]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 18:22:09,545]-[readConfig.py]-[line:26]-ERROR: 配置文件读取失败！
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\API_auto_test\common\readConfig.py", line 20, in read_config
    f = open(file=file_path, mode='r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\PycharmProjects\\API_auto_test\\test_data\\test_data.yaml'
[2023-02-13 18:22:34,362]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
[2023-02-13 18:22:34,363]-[readConfig.py]-[line:22]-INFO: 配置文件数据读取成功！
[2023-02-13 18:22:34,364]-[readConfig.py]-[line:19]-INFO: 正在读取配置文件中...
